Selection sort
Nephasis/Algorithms pull request #1
Opened 2017-08-26 13:38 UTC by Nephasis

2017-08-27 19:45 UTC, arathunku requested changes

2017-08-27 19:45 UTC, arathunku commented on selection_sort/selection_sort.js
> +  debugger;
??

2017-08-28 07:49 UTC, Nephasis commented on selection_sort/selection_sort.js
> +  debugger;
Forgot to delete if after playing a little bit with debugging (trying not to use console.log as you requested)

2017-09-14 18:37 UTC, arathunku requested changes

2017-09-14 18:37 UTC, arathunku commented on selection_sort/random_array.js
> +  return () => {
randomLetter doesn't need to return a function, it doesn't take any arguments so: f() => (b()) can be simplified to b() (errr... now I wish I remember notation from that from uni :P)

2017-10-02 16:46 UTC, merged